### ISSUE TITLE
check the fields in apply changes.

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#121]
Hi again, 
I have a problem with validate fields befores submit.
I have this simple code:
**************

Insertion position | Bottom of issue form
***************
$(function() {

  $('#issue-form input[type="submit"]')
    .on('click', function(event) {
     alert('Step 1');
      var tipoPeticion = $('#issue_tracker_id').val();
      var medida = $('#issue_custom_field_values_139 > option:selected').text();

      switch(tipoPeticion) {
          case '40':
          case '41':
          //LOTE 1
                    alert('Step 2');
                    if (medida == "0. Presupuesto ordinario" || medida == "P. Periferia" ) { alert('El Lote 1 solo admite imputación a presupuesto de Fondos Europeos, por favor, modifique la selección');return false; }
          break;
    
                       } // de switch
    }); // de function(event)
}); // de function()
***********************
The code, evaluate the tracker and a custom field.
When the combination is not correct must be send a alaert with the selected option with error.
The problem its that the message send more than one in the screen.
Include a video with the example.
I put a trace lines (step 1 and step 2 alerts) for verify the points of  the execution.

I don't underestand what is happen.
Regards 

https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/ea0e1eb9-070b-4bc5-a800-ece31b852393

**Comment by onozaty** [comment]
Input form is reloaded when tracker or project changes occur.
"Bottom of issue form" setting is useful because the script will be executed each time the input form is reloaded and can be applied to the input form after reloading.

However, since the submit button is not a part that is reloaded, event handlers are set repeatedly for the same button, resulting in this phenomenon.

If you change the Insertion position to "Head of all pages", it will work as you expect.
The script will be embedded in all pages, but this is not a problem since the issue-form element only exists on the Issue input screen.

Thanks.

**Comment by jlsblasco** [comment]
Thank you very very very much for the explanation and the solution.
You are my hero one more time.
Regards
