### ISSUE TITLE
Number of subtask in issue fields. And Average of subtasks.

### ISSUE THREAD

**Issue by SHNev** [onozaty/redmine-view-customize-scripts#128]
Hi Onozaty.
Hope you are doing well.
1. Can we get number of subtask in issue.
I have a fiels as integer, name as 'Number of subatask'
My requirement is to get number of subtask automatically.
If user Added 1 subtask then 'Number of subatask' should get value automatically as '1'
How to achieve this behaviour with javascript?

2. I  have two fields, one named as 'Total' which is only applicable for subtask, another named as 'Average Total' which is applicable for parent task. I want to show average of field 'Total' in 'Average Total' .
Means If I have Issue and it has two subtasks, one has value in 'Total' field as '90' another has '100'. Then Field 'Average Total' which is Field of parent task must show value as Answer
That is , [ (90 + 100) / 2] = 95.

Any way to achieve this behaviour through javascript?.

**Comment by onozaty** [comment]
Hi @SHNev 

> 1. Can we get number of subtask in issue.
>    I have a fiels as integer, name as 'Number of subatask'
>    My requirement is to get number of subtask automatically.
>    If user Added 1 subtask then 'Number of subatask' should get value automatically as '1'
>    How to achieve this behaviour with javascript?

The number of subtasks can be checked with the following code.

```javascript
$('#issue_tree tr.issue').length
```

However, it is difficult to automatically set this up as a custom field since it just counts what is on the screen.

> 2. I  have two fields, one named as 'Total' which is only applicable for subtask, another named as 'Average Total' which is applicable for parent task. I want to show average of field 'Total' in 'Average Total' .
>    Means If I have Issue and it has two subtasks, one has value in 'Total' field as '90' another has '100'. Then Field 'Average Total' which is Field of parent task must show value as Answer
>    That is , [ (90 + 100) / 2] = 95.
> 
> Any way to achieve this behaviour through javascript?.

To retrieve the value of a custom field in a child ticket, you must use the REST API.
You can use the REST API in View customize to access them, but it is not recommended because it is cumbersome code.

Also in this case, it is difficult to set the field automatically.

I have looked into whether there is another way to achieve both of these.
The following plugin may help, as it allows you to turn SQL results into custom fields.

*  https://www.redmine.org/plugins/custom_field_sql

Thanks.

**Comment by SHNev** [comment]
Ok.
Thanks Onozaty, I will try plugin you shared.
