### ISSUE TITLE
Done%

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#65]
Is there any way to added values to 
Done ratio (0,10,20,...100)
To be as example
( 0,5,10,15,25,.....,100)
this example
[https://stackoverflow.com/questions/5145689/is-it-possible-to-change-the-increment-value-for-the-done-field/5222787](url)
`<p><%= f.select :done_ratio, ((0..100).step(5).to_a.collect {|r| ["#{r} %", r] }) %></p>
`

how i can put this code in your plugin
thx

**Comment by ishikawa999** [comment]
It is possible to make the select box appear by replacing `$('#issue_done_ratio options')` in javascript.
Perhaps the following article will help: https://stackoverflow.com/questions/1801499/how-to-change-options-of-select-with-jquery
Replace the existing options with the following options:
```
<option value="5">5 %</option>
<option value="10">10 %</option>
<option value="15">15 %</option>
<option value="20">20 %</option>
...
```

However, when you save a value such as 35% and try to edit that screen, You can't get that 35% is already selected. (Since there is no 35% option in the select box before the replacement, there is no way to tell in the HTML what the selected value is.)
You might be able to get the existing value of done_ratio from the API and set it to the select box.

**Comment by ashrafalzyoud** [comment]
I found this solution 
[https://stackoverflow.com/questions/5145689/is-it-possible-to-change-the-increment-value-for-the-done-field/5222787]()
But not appear in status issues and bulk_edit
